In [1]:
import numpy as np
import torch

from legacyMTT import wilks_map, wilks_map_tensor

In [2]:
import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [3]:
im = np.random.rand(100,100)
im_tensor = torch.tensor(im)
radius = 1.1
n_pix = 7


In [4]:
m0, alpha, w_map = wilks_map(im, radius, n_pix)


In [5]:
m0_ten, alpha_ten, w_map_ten = wilks_map_tensor(im_tensor, radius, n_pix)

/Users/oandrews/PycharmProjects/DeepFit/legacyMTT.py:67: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:467.)
  r_indices = slice(torch.floor_divide((R - r), 2), torch.floor_divide((R - r), 2) + r)


In [6]:
print(m0)
print(m0_ten)


[[0.51559335 0.49180975 0.46430951 ... 0.50309857 0.49279845 0.51665332]
 [0.51851703 0.50983938 0.49847936 ... 0.51064976 0.51683577 0.52122573]
 [0.52466024 0.52566461 0.516364   ... 0.4878594  0.48136729 0.50272796]
 ...
 [0.54432975 0.53151718 0.50701966 ... 0.52045008 0.56002761 0.56448753]
 [0.52731344 0.51137312 0.48058673 ... 0.52603524 0.54195174 0.54771534]
 [0.52041836 0.50044162 0.46371301 ... 0.49681368 0.49365698 0.51590241]]
tensor([[0.5156, 0.4918, 0.4643,  ..., 0.5031, 0.4928, 0.5167],
        [0.5185, 0.5098, 0.4985,  ..., 0.5106, 0.5168, 0.5212],
        [0.5247, 0.5257, 0.5164,  ..., 0.4879, 0.4814, 0.5027],
        ...,
        [0.5443, 0.5315, 0.5070,  ..., 0.5205, 0.5600, 0.5645],
        [0.5273, 0.5114, 0.4806,  ..., 0.5260, 0.5420, 0.5477],
        [0.5204, 0.5004, 0.4637,  ..., 0.4968, 0.4937, 0.5159]],
       dtype=torch.float64)


In [10]:
print(np.abs((m0-m0_ten.numpy())/m0))

[[1.05978288e-08 9.41624610e-09 9.27050649e-09 ... 3.66704328e-09
  1.82028954e-08 7.93075599e-09]
 [5.45163031e-09 3.87152401e-09 4.46523430e-09 ... 7.81872639e-09
  7.95615671e-09 4.70544698e-09]
 [2.89698308e-09 7.33502155e-10 3.56807511e-09 ... 9.89416134e-09
  1.13883024e-08 7.82074944e-09]
 ...
 [2.91333887e-09 6.48617032e-09 6.88631058e-10 ... 3.63041316e-09
  1.55964252e-09 5.35427199e-09]
 [8.46456950e-09 4.83503765e-09 1.10072085e-08 ... 8.24682112e-09
  7.65598161e-09 2.81661732e-09]
 [3.56739640e-09 4.38206566e-10 5.90571541e-09 ... 6.55418162e-09
  1.16590341e-08 3.95964236e-09]]


In [11]:
np.max((np.abs((m0-m0_ten.numpy())/m0)))

2.7074897341405612e-08

In [12]:
np.max((np.abs((alpha-alpha_ten.numpy())/alpha)))

3.175933914124022e-08

In [13]:
np.max((np.abs((w_map-w_map_ten.numpy())/w_map)))

2.3316743542177862e-08

In [ ]:
## Looks good to me